
#actuator configuration
info:
  app:
    name: client services
    description: client service
    version: 0.0.1
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
        
