
#actuator configuration
info:
  app:
    name: client services
    description: client service
    version: 0.0.1
management:
  endpoints:
    web:
      exposure:
        include: '*'
        base-path: bootcamp51/ms/client/actuator
