server:
  port: 9010 #${port:0}

### Mongo database configuration
spring:
  data:
    mongodb:
      uri: mongodb://bootcamp51:bootcamp51@localhost:27017/bootcamp51?authSource=admin


#actuator configuration
info:
  app:
    name: client services
    description: client service
    version: 0.0.1

management:
  endpoints:
    web:
      exposure:
        include: '*'
        base-path: /actuator

rutaApiClient: "http://localhost:9020/bootcamp51/ms/product"
retryApiClient: 3
timeIntervalApiClient: 3