server:
  port: 9020 #${port:0}
  servlet:
    context-path: /management/licensesissuance/api/dev/driverslicense

### Mongo database configuration
spring:
  data:
    mongodb:
      uri: mongodb://licensesissuance:licensesissuance@localhost:27017/driverslicense?authSource=admin
          #  mongodb://mitocode  :mitocode. @localhost:27017/mitocode  ?authSource=admin
      # uri: mongodb://192.168.1.51:27017/bootcamp51?authSource=admin
# mongodb://bootcamp51:bootcamp51@localhost:27017/bootcamp51?authSource=admin
#  webflux:
#    base-path: /bootcamp51/ms/client


#actuator configuration
info:
  app:
    name: client services
    description: client service
    version: 0.0.1
management:
  endpoints:
    web:
      exposure:
        include: '*'
        base-path: bootcamp51/ms/client/actuator


#resilience4j:
#  circuitbreaker:
#    configs:
#      customConfig:  # RATIO DE ERRORES
#        slidingWindowSize: 12 # cantidad de peticiones
#        failureRateThreshold: 40 #porcentaje de caidas
#        waitDurationInOpenState: 10s # tiempo de abierto - despues pasa a un estado semi abierto
#        permittedNumberOfCallsInHalfOpenState: 8 # cantidad de muestra pruebas en semi abierto
#        # LLAMADAS LENTAS
#        slowCallRateThreshold: 20 # porcentaje de llamada lentas
#        slowCallDurationThreshold: 500ms #tiempo de respuesta si la cantidad de peticiones de 50% supera el tiempo de respuesta el servicio se puede abrir
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#    instances:
#      mitocode-product: # Nombre a mapear dentro del @CircuitBreaker
#        base-config: product-service-cb
#      mitocode-user:
#        base-config: user-service-cb      
#



rutaApiClient: "http://localhost:9020/bootcamp51/ms/product"
retryApiClient: 3
timeIntervalApiClient: 3