server:
  port: 9020 #${port:0}
  servlet:
    context-path: /management/licensesissuance/api/dev/driverslicense

### Mongo database configuration
spring:
  data:
    mongodb:
      uri: mongodb://licensesissuance:licensesissuance@localhost:27017/driverslicense?authSource=admin
          #  mongodb://mitocode  :mitocode. @localhost:27017/mitocode  ?authSource=admin
      # uri: mongodb://192.168.1.51:27017/bootcamp51?authSource=admin
# mongodb://bootcamp51:bootcamp51@localhost:27017/bootcamp51?authSource=admin
#  webflux:
#    base-path: /bootcamp51/ms/client


#actuator configuration
info:
  app:
    name: client services
    description: client service
    version: 0.0.1
management:
  endpoints:
    web:
      exposure:
        include: '*'
        base-path: bootcamp51/ms/client/actuator

resilience4j:
  circuitbreaker:
    configs:
      client-service-cb:
        slidingWindowSize: 12
        failureRateThreshold: 40
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 8
        slowCallRateThreshold: 20
        slowCallDurationThreshold: 500ms
        automaticTransitionFromOpenToHalfOpenEnabled: true

    instances:
      client-service:
        base-config: client-service-cb
  



rutaApiClient: "http://localhost:9020/bootcamp51/ms/product"
retryApiClient: 3
timeIntervalApiClient: 3