server:
  port: 9020 #${port:0}
  # servlet:
  #   context-path: /bootcamp51/ms/client




### Mongo database configuration
spring:
  data:
    mongodb:
      uri: mongodb://bootcamp51:bootcamp51@192.168.1.54:27017/bootcamp51?authSource=admin
          #  mongodb://mitocode  :mitocode. @localhost:27017/mitocode  ?authSource=admin
      # uri: mongodb://192.168.1.51:27017/bootcamp51?authSource=admin
# mongodb://bootcamp51:bootcamp51@localhost:27017/bootcamp51?authSource=admin
  webflux:
    base-path: /bootcamp51/ms/product


#actuator configuration
info:
  app:
    name: product services
    description: product service
    version: 0.0.1
management:
  endpoints:
    web:
      exposure:
        include: '*'
        base-path: bootcamp51/ms/product/actuator

rutaApiClient: "http://localhost:9020/bootcamp51/ms/product"
retryApiClient: 3
timeIntervalApiClient: 3